package com.ejemplo.carmenuy.ui.rc;




import com.ejemplo.carmenuy.control.ControladorLogin2;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author 32681391
 */
public class RegistroCuenta extends javax.swing.JFrame {
    
    private static RegistroCuenta instancia; // autoreferencia


    /**
     * Creates new form RegistroCuenta
     */
    private RegistroCuenta() {
        initComponents();
        jBtnAceptar.addActionListener(ControladorLogin2.obtenerInstancia());

    }
    
    public static RegistroCuenta obtenerInstancia() {
        if (instancia == null) {
            instancia = new RegistroCuenta();
            
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        labRegistro = new javax.swing.JLabel();
        labApellido = new javax.swing.JLabel();
        labNombre1 = new javax.swing.JLabel();
        labContraseña = new javax.swing.JLabel();
        labRepetirContraseña = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jPasswordRepetirContra = new javax.swing.JPasswordField();
        jPasswordContraseña = new javax.swing.JPasswordField();
        jBtnAceptar = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labRegistro.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        labRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labRegistro.setText("Registrate al fabuloso juego de CSDuy");

        labApellido.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labApellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labApellido.setText("Apellido");

        labNombre1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labNombre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labNombre1.setText("Nombre");

        labContraseña.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labContraseña.setText("Contraseña");

        labRepetirContraseña.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labRepetirContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labRepetirContraseña.setText("Repetir contraseña");

        jPasswordContraseña.setToolTipText("");

        jBtnAceptar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(labRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labRepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordContraseña)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPasswordRepetirContra, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(jTextNombre)
                                        .addComponent(jTextApellido)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labRegistro)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNombre1)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labApellido)
                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labContraseña)
                    .addComponent(jPasswordContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labRepetirContraseña)
                    .addComponent(jPasswordRepetirContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCuenta().setVisible(true);
            }
        });
    }

    public RegistroCuenta(JButton jBtnAceptar, JPasswordField jPasswordContraseña, JPasswordField jPasswordRepetirContra, JTextField jTextApellido, JTextField jTextEdad, JTextField jTextNombre, JLabel labApellido, JLabel labContraseña, JLabel labEdad, JLabel labNombre1, JLabel labRegistro, JLabel labRepetirContraseña) throws HeadlessException {
        this.jBtnAceptar = jBtnAceptar;
        this.jPasswordContraseña = jPasswordContraseña;
        this.jPasswordRepetirContra = jPasswordRepetirContra;
        this.jTextApellido = jTextApellido;
        this.jTextNombre = jTextNombre;
        this.labApellido = labApellido;
        this.labContraseña = labContraseña;
        this.labNombre1 = labNombre1;
        this.labRegistro = labRegistro;
        this.labRepetirContraseña = labRepetirContraseña;
    }

    public JButton getjBtnAceptar() {
        return jBtnAceptar;
    }

    public JPasswordField getjPasswordContraseña() {
        return jPasswordContraseña;
    }

    public JPasswordField getjPasswordRepetirContra() {
        return jPasswordRepetirContra;
    }

    public JTextField getjTextApellido() {
        return jTextApellido;
    }

   
    public JTextField getjTextNombre() {
        return jTextNombre;
    }

    public JLabel getLabApellido() {
        return labApellido;
    }

    public JLabel getLabContraseña() {
        return labContraseña;
    }

    public JLabel getLabNombre1() {
        return labNombre1;
    }

    public JLabel getLabRegistro() {
        return labRegistro;
    }

    public JLabel getLabRepetirContraseña() {
        return labRepetirContraseña;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JPasswordField jPasswordContraseña;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordRepetirContra;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JLabel labApellido;
    private javax.swing.JLabel labContraseña;
    private javax.swing.JLabel labNombre1;
    private javax.swing.JLabel labRegistro;
    private javax.swing.JLabel labRepetirContraseña;
    // End of variables declaration//GEN-END:variables

    public void mostrarMensaje(String msj) {
        JOptionPane.showMessageDialog(null, msj);
    }
}
