package com.ejemplo.carmenuy.ui.rc;

import com.ejemplo.carmenuy.control.ControladorLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author 32681391
 */
public class VBienvenida extends javax.swing.JFrame {

    private static VBienvenida instancia; // autoreferencia

    private JPanel jPanel1;
    private JLabel jLabBienvenidos;
    private JTextArea jTextArIntro;
    private JButton jBtn1IniciarJuego;
    private JLabel jLabImagenj;
    private JScrollPane jScrollPane1;
    private String intro;

    /* Creates new form VBienvenida
     */
    private VBienvenida() {
        initComponents();
        this.setLocationRelativeTo(null);
        jBtn1IniciarJuego.addActionListener(ControladorLogin.obtenerInstancia());
    }

    // SINGLETON (patrón de diseño)
    public static VBienvenida obtenerInstancia() {
        if (instancia == null) {
            instancia = new VBienvenida();
        }
        return instancia;
    }

    /*private void initComponents() {
        setTitle("Juego");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        jPanel1 = new JPanel();
        jPanel1.setBounds(200, 200, 400, 200);
        jPanel1.setLayout(null);
        add(jPanel1);

        jLabBienvenidos = new JLabel("Bienvenido al Juego");
        jLabBienvenidos.setBounds(150, 50, 200, 25);
        jLabBienvenidos.add(jLabBienvenidos);

        jBtn1IniciarJuego = new JButton("Iniciar Juego");
        jBtn1IniciarJuego.setBounds(150, 100, 120, 25);
        jBtn1IniciarJuego.add(jBtn1IniciarJuego);

        jBtn1IniciarJuego.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jBtn1IniciarJuegoActionPerformed(evt);
            }
        });

         add(  jPanel1);
       
        intro = "¡Detective, tu misión comienza ahora!\n\n" +
                "Carmen Sandiego, la maestra del disfraz y la reina del robo, ha vuelto a hacer de las suyas. Esta vez, ha puesto su mirada en los tesoros culturales, históricos y naturales de Uruguay. Tu tarea es seguir sus pistas y detenerla antes de que desaparezca con los valiosos patrimonios de nuestro hermoso país.\n\n" +
                "¿Cómo jugar?\n" +
                "Sigue las pistas: Carmen ha dejado pistas a lo largo de los 19 departamentos de Uruguay. Usa tu ingenio y conocimientos para seguir su rastro.\n" +
                "Resuelve acertijos: Cada pista te llevará a resolver acertijos que te acercarán más a su paradero.\n" +
                "Explora Uruguay: Aprende sobre la geografía, historia y cultura de Uruguay mientras persigues a Carmen por todo el país.\n" +
                "Captura a Carmen: Reúne suficientes pruebas y atrapa a Carmen antes de que logre escapar de nuevo.\n\n" +
                "¡Comencemos la aventura!\n" +
                "Haz clic en \"Iniciar Juego\" para empezar tu búsqueda. Buena suerte, detective. ¡El destino de los tesoros uruguayos está en tus manos!";
            
            jPanel1.add(jTextArIntro);
            jTextArIntro= new JTextArea(intro);
            jTextArIntro.setBounds(50, 60, 600, 300);
            jTextArIntro.setLineWrap(true);
            jTextArIntro.setWrapStyleWord(true);
            jTextArIntro.setEditable(false);
            jTextArIntro.setBackground( jPanel1.getBackground());
        jPanel1.add(    jTextArIntro);
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabBienvenidos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArIntro = new javax.swing.JTextArea();
        jLabImagenj = new javax.swing.JLabel();
        jBtn1IniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a ¿Dónde, en Uruguay, está CarmenSandiego?");
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(630, 420));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 420));

        jLabBienvenidos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabBienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabBienvenidos.setText("Bienvenid@s al juego ¿Dónde, en Uruguay,  está Carmen Sandiego?");

        jTextArIntro.setEditable(false);
        jTextArIntro.setColumns(20);
        jTextArIntro.setForeground(new java.awt.Color(153, 0, 0));
        jTextArIntro.setLineWrap(true);
        jTextArIntro.setRows(20);
        jTextArIntro.setText("¡Detective, tu misión comienza ahora!\n                Carmen Sandiego, la maestra del disfraz y la reina del robo, ha vuelto a hacer de las suyas. Esta vez, ha puesto su mirada en los tesoros culturales, históricos y naturales de Uruguay.\n\n Tu tarea es seguir sus pistas y detenerla antes de que desaparezca con los valiosos patrimonios de nuestro hermoso país.\n\n\n                ¿Cómo jugar?\n                Sigue las pistas: Carmen ha dejado pistas a lo largo de los 19 departamentos de Uruguay. Usa tu ingenio y conocimientos para seguir su rastro.\n                Resuelve acertijos: Cada pista te llevará a resolver acertijos que te acercarán más a su paradero.\n\n\n                Explora Uruguay: Aprende sobre la geografía, historia y cultura de Uruguay mientras persigues a Carmen por todo el país.\n                Captura a Carmen: Reúne suficientes pruebas y atrapa a Carmen antes de que logre escapar de nuevo.\n                ¡Comencemos la aventura!\n                Haz clic en \"Iniciar Juego\" para empezar tu búsqueda. Buena suerte, detective. ¡El destino de los tesoros uruguayos está en tus manos!\n            ");
        jTextArIntro.setWrapStyleWord(true);
        jTextArIntro.setBorder(null);
        jTextArIntro.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTextArIntroComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArIntro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabBienvenidos)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabBienvenidos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabImagenj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBtn1IniciarJuego.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jBtn1IniciarJuego.setForeground(new java.awt.Color(102, 102, 102));
        jBtn1IniciarJuego.setText("Iniciar Juego");
        jBtn1IniciarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn1IniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1IniciarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabImagenj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtn1IniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabImagenj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn1IniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(137, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn1IniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1IniciarJuegoActionPerformed
    }//GEN-LAST:event_jBtn1IniciarJuegoActionPerformed

    private void jTextArIntroComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextArIntroComponentShown
        // TODO add your handling code here:
        jTextArIntro = new JTextArea(intro);
        jPanel1.add(jTextArIntro);
    }//GEN-LAST:event_jTextArIntroComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //VJuego juego = new VBienvenida();
        //juego.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn1IniciarJuego;
    private javax.swing.JLabel jLabBienvenidos;
    private javax.swing.JLabel jLabImagenj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArIntro;
    // End of variables declaration//GEN-END:variables

        });

    }

    public JPanel getJPanel1() {
        return jPanel1;
    }

    public JLabel getJLabBienvenido() {
        return jLabBienvenidos;
    }

    public JTextArea jTextArIntro() {
        return jTextArIntro;
    }

    public JButton getjBtn1IniciarJuego() {
        return jBtn1IniciarJuego;
    }

    public JLabel getjLabImagenj() {
        return jLabImagenj;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public String getIntro() {
        return intro;
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
}
