package com.ejemplo.carmenuy.ui.rc;
import com.ejemplo.carmenuy.database.DatabaseInitialization;
import com.ejemplo.carmenuy.dao.LocalidadDAO;
import com.ejemplo.carmenuy.model.Localidad;
import com.ejemplo.carmenuy.model.Localidad2;
import java.sql.SQLException;
import modelo.*;
import javax.swing.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.ejemplo.carmenuy.model.MapaDeUruguay;

public class VJuego2 extends JFrame{
    
    private static VJuego2 instancia; // autoreferencia

    /**
     * @author 32681391
     */
    private MapaDeUruguay mapa;
    private List<Localidad> localidades;

    private VJuego2() {
        initComponents();
        //mapa = new MapaDeUruguay();
        //localidades = mapa.getLocalidades();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
        public static VJuego2 obtenerInstancia() {
        if (instancia == null) {
            instancia = new VJuego2();
        }
        return instancia;
    }
    
    /*
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Aquí debes agregar el código para dibujar el mapa de fondo
        // Por ejemplo, si tienes una imagen del mapa:
        // ImageIcon mapa = new ImageIcon("ruta/al/mapa.png");
        // g.drawImage(mapa.getImage(), 0, 0, this);

        // Dibujar los puntos de interés
        for (Localidad punto : localidades) {
            // Suponiendo que ya has transformado latitud y longitud a coordenadas x e y
            int x = transformarLongitud(punto.getLongitud());
            int y = transformarLatitud(punto.getLatitud());
            g.fillOval(x, y, 10, 10); // Dibujar el punto
        }
    }

    private int transformarLatitud(double latitud) {
        // Implementa la lógica para transformar latitud a coordenada y
        return (int) ((latitud + 35) * getHeight() / 70); // Ajusta según sea necesario
    }

    private int transformarLongitud(double longitud) {
        // Implementa la lógica para transformar longitud a coordenada x
        return (int) ((longitud + 57) * getWidth() / 114); // Ajusta según sea necesario
    }

    public MapaPanel(LayoutManager layout, boolean isDoubleBuffered) {
        super(layout, isDoubleBuffered);
    }
    */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabMapa = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        ElegirLugar = new javax.swing.JButton();
        PISTA = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 470));

        jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MapaUruguay chico.jpg"))); // NOI18N
        jLabMapa.setLabelFor(jLabMapa);

        Buscar.setText("BUSCAR SECUAZ");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        ElegirLugar.setText("ELEGIR LOCALIDAD");
        ElegirLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirLugarActionPerformed(evt);
            }
        });

        PISTA.setText("PISTA");
        PISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PISTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PISTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ElegirLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(Buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(ElegirLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(PISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void ElegirLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirLugarActionPerformed
        Object [] departamentos ={"Artigas","Salto","Paysandú","Rio Negro","Rivera","Tacuarembo","Soriano", "Flores", "Cerro Largo","Durazno", "Rocha", "Florida", "Lavalleja", "Treinta y Tres", "Canelones", "San José", "Maldonado", "Colonia", "Montevideo"};
        Object seleccion=JOptionPane.showInputDialog(null,"Selecciona un departamento", "Elegir",JOptionPane.QUESTION_MESSAGE,null,departamentos, departamentos[0]);
        System.out.println(seleccion.toString());
        if(seleccion.toString()!=null){
            switch (seleccion.toString()) {
             case "Artigas":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/artigas.jpg")));
                break; 
             case "Salto":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salto.jpg")));
                break; 
              case "Paysandú":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paysandu.jpg")));
                break; 
              case "Rio Negro":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rio negro.jpg")));
                break;   
                 case "Rivera":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rivera.jpg")));
                break; 
             case "Tacuarembo":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tacuarembo.jpg")));
                break;  
             case "Soriano":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/soriano.jpg")));
                break;   
             case "Flores":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flores.jpg")));
                break;     
             case "Cerro Largo":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrolargo.jpg")));
                break;   
             case "Durazno":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/durazno.jpg")));
                break;     
             case "Rocha":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rocha.jpg")));
                break;
             case "Florida":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/florida.jpg")));
                break;   
             case "Lavalleja":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lavalleja.jpg")));
                break;  
              case "Treinta y Tres":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/treinta y tres.jpg")));
                break;   
             case "Canelones":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canelones.jpg")));
                break;  
             case "San José":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/san jose.jpg")));
                break; 
             case "Maldonado":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Maldonadoo.jpg")));
                break;   
              case "Colonia":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colonia"
                        + ".jpg")));
                break;      
             case "Montevideo":
                jLabMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Montevideo.jpg")));
                break; 
            default:
                throw new AssertionError();
            }
        }
        
    }//GEN-LAST:event_ElegirLugarActionPerformed

    private void PISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PISTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PISTAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton ElegirLugar;
    private javax.swing.JButton PISTA;
    private javax.swing.JLabel jLabMapa;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VJuego2().setVisible(true);
            }
        });
    }
    
        public List<Localidad> getLocalidades() {
        return localidades;
    }

    public JButton getBuscar() {
        return Buscar;
    }

    public JButton getElegirLugar() {
        return ElegirLugar;
    }

    public JButton getPISTA() {
        return PISTA;
    }

    public JLabel getjLabMapa() {
        return jLabMapa;
    }

    public void setLocalidades(List<Localidad> localidades) {
        this.localidades = localidades;
    }

    public void setBuscar(JButton Buscar) {
        this.Buscar = Buscar;
    }

    public void setElegirLugar(JButton ElegirLugar) {
        this.ElegirLugar = ElegirLugar;
    }

    public void setPISTA(JButton PISTA) {
        this.PISTA = PISTA;
    }

    public void setjLabMapa(JLabel jLabMapa) {
        this.jLabMapa = jLabMapa;
    }

}
